// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../sdimage_ui.h"
#include "./assets.h"


lv_obj_t * ui_Screen_sdimage = NULL;
lv_obj_t * ui_sdimage_Button_Button1 = NULL;
lv_obj_t * ui_sdimage_Label_Label1 = NULL;
// event funtions
void ui_event_sdimage_Button_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sdimage_key_prtSc(e);
    }
}
// build funtions

void ui_Screen_sdimage_screen_init(void)
{
      ui_Screen_sdimage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_sdimage, LV_OBJ_FLAG_SCROLLABLE);      

    ui_sdimage_Button_Button1 = lv_btn_create(ui_Screen_sdimage);
    lv_obj_set_width(ui_sdimage_Button_Button1, 100);
    lv_obj_set_height(ui_sdimage_Button_Button1, 50);
    lv_obj_set_x(ui_sdimage_Button_Button1, -281);
    lv_obj_set_y(ui_sdimage_Button_Button1, -194);
    lv_obj_set_align(ui_sdimage_Button_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sdimage_Button_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_sdimage_Button_Button1, LV_OBJ_FLAG_SCROLLABLE);

    ui_sdimage_Label_Label1 = lv_label_create(ui_sdimage_Button_Button1);
    lv_obj_set_width(ui_sdimage_Label_Label1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_sdimage_Label_Label1, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_sdimage_Label_Label1, -1);
    lv_obj_set_y(ui_sdimage_Label_Label1, 1);
    lv_obj_set_align(ui_sdimage_Label_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sdimage_Label_Label1, "截图");
    lv_obj_set_style_text_color(ui_sdimage_Label_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sdimage_Label_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sdimage_Label_Label1, &font_puhui_20_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_sdimage_Button_Button1, ui_event_sdimage_Button_Button1, LV_EVENT_ALL, NULL);
    sdimage_init();
}

void ui_Screen_sdimage_screen_destroy(void)
{
    if(ui_Screen_sdimage) lv_obj_del(ui_Screen_sdimage);

    ui_Screen_sdimage = NULL;
    ui_sdimage_Button_Button1 = NULL;
    ui_sdimage_Label_Label1 = NULL;

}


