// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Screen1
extern void ui_Screen_sdimage_screen_init(void);
extern void ui_Screen_sdimage_screen_destroy(void);
extern lv_obj_t * ui_Screen_sdimage;
extern lv_obj_t * ui_sdimage_Button_Button1;
extern lv_obj_t * ui_sdimage_Label_Label1;
extern void ui_event_sdimage_Button_Button1(lv_event_t * e);
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif





