// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../homeass_ui.h"
#include "./assets.h"


lv_obj_t * ui_Screen_assets = NULL;
lv_obj_t * ui_assets_Button_Button1 = NULL;
lv_obj_t * ui_assets_Label_Label1 = NULL;
// event funtions
void ui_event_assets_Button_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        toggle_light(e);
    }
}
// build funtions

void ui_Screen_assets_screen_init(void)
{
      ui_Screen_assets = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_assets, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_assets_Button_Button1 = lv_btn_create(ui_Screen_assets);
    lv_obj_set_width(ui_assets_Button_Button1, 100);
    lv_obj_set_height(ui_assets_Button_Button1, 50);
    lv_obj_set_x(ui_assets_Button_Button1, -281);
    lv_obj_set_y(ui_assets_Button_Button1, -194);
    lv_obj_set_align(ui_assets_Button_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_assets_Button_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_assets_Button_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_assets_Label_Label1 = lv_label_create(ui_assets_Button_Button1);
    lv_obj_set_width(ui_assets_Label_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_assets_Label_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_assets_Label_Label1, -1);
    lv_obj_set_y(ui_assets_Label_Label1, 1);
    lv_obj_set_align(ui_assets_Label_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_assets_Label_Label1, "卧室灯");
    lv_obj_set_style_text_color(ui_assets_Label_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_assets_Label_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_assets_Label_Label1, &font_puhui_20_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_assets_Button_Button1, ui_event_assets_Button_Button1, LV_EVENT_ALL, NULL);
    http_ctrl_init();
}

void ui_Screen_assets_screen_destroy(void)
{
    if(ui_Screen_assets) lv_obj_del(ui_Screen_assets);

    // NULL screen variables
    ui_Screen_assets = NULL;
    ui_assets_Button_Button1 = NULL;
    ui_assets_Label_Label1 = NULL;

}
